// orb-extension-sdk: type surface of @earendil-works/pi-agent-core (upstream pi 1.0.0, commit a13d35a7, MIT © Mario Zechner).
// Generated by conformance/extract/sdk-surface.mjs from the pinned upstream package sources.
// Every upstream export name is declared so Node type-stripping and the loader's
// type-only-import classifier see the same surface as the real package.

// Value exports (8; 0 implemented, the rest are unsupported stubs at runtime):
export declare const Agent: any;
export declare const agentLoop: any;
export declare const agentLoopContinue: any;
export declare const runAgentLoop: any;
export declare const runAgentLoopContinue: any;
export declare const runToolCall: any;
export declare const setDefaultStreamFn: any;
export declare const streamProxy: any;

// Type-only exports (34):
export type AfterToolCallContext = any;
export type AfterToolCallResult = any;
export type AgentContext = any;
export type AgentEvent = any;
export type AgentEventSink = any;
export type AgentInitialState = any;
export type AgentLoopConfig = any;
export type AgentLoopTurnUpdate = any;
export type AgentMessage = any;
export type AgentOptions = any;
export type AgentRequestUpdate = any;
export type AgentState = any;
export type AgentTool = any;
export type AgentToolCall = any;
export type AgentToolCallOutcome = any;
export type AgentToolResult = any;
export type AgentToolUpdateCallback = any;
export type AgentTurnContext = any;
export type AgentTurnDecision = any;
export type BeforeToolCallContext = any;
export type BeforeToolCallResult = any;
export type CustomAgentMessages = any;
export type FinishTurn = any;
export type PrepareNextTurnContext = any;
export type PrepareRequest = any;
export type PrepareRequestContext = any;
export type ProxyAssistantMessageEvent = any;
export type ProxyStreamOptions = any;
export type QueueMode = any;
export type RunToolCallOptions = any;
export type StreamFn = any;
export type ThinkingLevel = any;
export type ToolCallHooks = any;
export type ToolExecutionMode = any;
