// orb-extension-sdk: type surface of @earendil-works/pi-ai/models (upstream pi 1.0.0, commit a13d35a7, MIT © Mario Zechner).
// Generated by conformance/extract/sdk-surface.mjs from the pinned upstream package sources.
// Every upstream export name is declared so Node type-stripping and the loader's
// type-only-import classifier see the same surface as the real package.

// Value exports (10; 1 implemented, the rest are unsupported stubs at runtime):
export declare const ModelsError: any;
export declare const calculateCost: any;
export declare const clampThinkingLevel: any;
export declare const createModels: any;
export declare const createProvider: any;
export declare const getModelType: any;
export declare const getSupportedThinkingLevels: any;
export declare const hasApi: any;
export declare const isModelType: any;
export declare const modelsAreEqual: any;

// Type-only exports (17):
export type CreateModelsOptions = any;
export type CreateProviderOptions = any;
export type Models = any;
export type ModelsApiStreamOptions = any;
export type ModelsClassifierOptions = any;
export type ModelsDeferredCancelOptions = any;
export type ModelsDeferredFetchOptions = any;
export type ModelsErrorCode = any;
export type ModelsImagesOptions = any;
export type ModelsPublication = any;
export type ModelsRefreshOptions = any;
export type ModelsRefreshResult = any;
export type ModelsRequestTransforms = any;
export type ModelsSimpleStreamOptions = any;
export type MutableModels = any;
export type Provider = any;
export type RefreshModelsContext = any;
