// orb-extension-sdk: type surface of @earendil-works/pi-ai/providers/all (upstream pi 1.0.0, commit a13d35a7, MIT © Mario Zechner).
// Generated by conformance/extract/sdk-surface.mjs from the pinned upstream package sources.
// Every upstream export name is declared so Node type-stripping and the loader's
// type-only-import classifier see the same surface as the real package.

// Value exports (12; 0 implemented, the rest are unsupported stubs at runtime):
export declare const builtinModels: any;
export declare const builtinProviders: any;
export declare const getAllBuiltinModels: any;
export declare const getBuiltinClassifierModel: any;
export declare const getBuiltinClassifierModels: any;
export declare const getBuiltinImageModel: any;
export declare const getBuiltinImageModels: any;
export declare const getBuiltinModel: any;
export declare const getBuiltinModelDataGeneratedAt: any;
export declare const getBuiltinModels: any;
export declare const getBuiltinProviders: any;
export declare const radiusProvider: any;

// Type-only exports (1):
export type BuiltinProvider = any;
